### ISSUE TITLE
Support for CraftCMS 3 and PHP 7.1+

### ISSUE THREAD

**Issue by jasonandres** [sjelfull/Craft-CloudFrontInvalidation#7]
I see the current support listed in the README, copied below, curious if anyone has tried this on CraftCMS 3.x with success?

CloudFront invalidation works on Craft 2.4.x, Craft 2.5.x and Craft 2.6.x, and requires PHP 5.4.* or higher.

**Comment by sjelfull** [comment]
This hasn't been ported to Craft 3, but i'm open to pull requests if anyone want to take a stab at it.

**Comment by jamesmacwhite** [comment]
I can vouch for the PHP 7.1 support in Craft 2, as it works fine on a Craft 2 project I look after, in terms of Craft 3, I believe the AWS S3 plugin has native support for performing invalidations when you do certain actions, i.e update or delete automatically.

I certainly don't mean any disrespect to sjelfull, because this plugin is very useful for Craft 2, but you probably won't need it in Craft 3.

**Comment by sjelfull** [comment]
@jamesmacwhite Correct, the AWS S3 plugin does indeed handle CloudFront invalidation.

I'm gonna close this for now.
